### PR TITLE
All Matching Regex

### PR DESCRIPTION
**Pull request by JohnMoutafis**
Added a utility method, able to read a multitude of user input from `tracks txt`.

Other changes (minor):
- Updated the dev branch to be in sync with the master branch.
- Made code of the parsing part of `split.py` DRY.
- Erased `tracks.txt` from the repository and added a `tracks.txt.example` in it's place, because it is a configuration file, thus it is better to be environment specific.

### CODE REVIEW

**Comment by crisbal** [comment]
I will review this in the afternoon, thanks a lot!

**Comment by JohnMoutafis** [comment]
Note also that this refs: #5 because it provides an easier way to edit `tracks.txt`, by accepting more types of text input format.

**Comment by crisbal** [comment]
Yes, that input parsing function is very very beautiful, amazing job there!

There are a few edge cases I found

```python
>> all_matching_regex("1 - 1:12:00 - hello 32") # dash instead of a dot for the track number
('1:12:00', '- hello 32')
# There is a dash inside the title
```


```python
>>> all_matching_regex("1:12:00 - hello 12:13") # time inside the title of the song
('1:12:00', 'hello')
# The `12:13` in the title is ignored
```

Not sure if these are easy fix, let me know.


Also we should update the README, I could do this if you don't want to.

**Comment by JohnMoutafis** [comment]
- Added the update for the edge cases mentioned
- Updated Readme.

Thanks for your comment :)

**Comment by crisbal** [comment]
Thanks again! Great job!

**Comment by crisbal** [comment]
Hey, I removed a regex in commit #4d8435341139c18f9f7aeef27e5b73bf08781597

It was causing a problem for songs that started with a number (for example "21 Guns" from Green Day was getting recognized as "Guns").

If you see any potential problem in this, let me know. 

I also updated my code a little bit, I wrote this a few years back so it needed some cleaning.

**Comment by crisbal** [comment]
Hey, 

I am writing tests for track_parser, right now I expect this: 

```python
self.assertEqual(track_parser("12:32"), ("", ""))
```

but I get `('12:32', '')`

Do you think it should return ('', '') or ('12:32', '')?

**Comment by JohnMoutafis** [comment]
I haven't considered what happens on fail. 
If we are to follow the zen of python, nothing should fail silently. In that case, we should define what a bad input is and what we should respond to it.

- I believe that just a timestamp should result on an empty title but work
- Empty time and title should fail
- Only title should fail

What is your take on the matter?

**Comment by crisbal** [comment]
First of all I think we should throw an exception instead of returning an empty tuple. 

Now that I think more on this, I also agree that just timestamp should work, but we have to handle the empty title somehow, for example naming the tracks with their position.

**Comment by JohnMoutafis** [comment]
- It can just fail, notify the user and he can fix it and restart.

- Or a bit more complicated but interesting, if a title is empty, prompt for user input!

**Pull request merged**
