### PR TITLE
Added ability to scan wikipedia pages for track names and times

### PR DESCRIPTION
**Pull request by inondle**
Hi crisbal,

Added this small feature as a way to add a little automation to a kinda tedious task. Since the youtube comments lack an official format they are a little harder to work with. Wikipedia (for the most part) has a consistent format for their wikipedia pages on track listings. 

The commits just add a few methods for scanning those wikipedia pages. I also used the lynx browser to get the webpage content mostly out of ease of use. If you think it's worth it doing the same purely with python is probably possible and I can rework it for that. My python isn't the best so feel free to rewrite it as you see fit if I did something inefficiently or confusingly. Also first pull request. 

By the way, great job on the album splitting! I wish I would have thought of this earlier. You should really think about maybe adding this somehow to the main youtube-dl project. Anyways look over it and get back to me if I need to change anything. Have a good weekend!

Best Regards, 
Inondle

### CODE REVIEW

**Comment by crisbal** [comment]
Nice idea! I will take a look at the code and merge the pull. 

What about using a library for web requests (requests for example) instead of a command line browser? It works the same but not everyone has lynx instslled. 


If you don't want to do it I will when I have some free time.

Thanks for this feature I really like it.

**Comment by crisbal** [comment]
I looked at the code. 

I have not tested it but I think I found a problem.

Right now the only way to split is by telling the program when a certain track starts (time since beginning), wikipedia instead lists tracks lenght, not tracks start time. Looking at the code it seems that you are pulling the length of the track, unless I am wrong. 

I hope you understand what I am trying to say.

Wikipedia has this:
Title - Length
1.	"Thirteen"  	3:04
2.	"Shark"  	5:01
3.	"Crayon"  	3:10

I need 

Title - When does it start?
1.	"Thirteen"  	0:00
2.	"Shark"  	3:04
3.	"Crayon"  	3:04+5:01

**Comment by inondle** [comment]
Hi, 

Reconfigured it to 1) not use lynx (instead uses urllib2 and BeautifulSoup), and 2) crunches the time numbers so it tracks elapsed time of each successive song. Once again look it over and I made a mistake let me know. 

Thanks!

**Comment by crisbal** [comment]
Thanks a lot! I tested it and it works! Merged.

Thanks especially for developing the part that handles the conversion track length <-> start time.

I changed the wikiurl parameter from "-u" to "-w" and I added some simple error handling if the script can't find the tracks table in the Wiki page. I hope you don't mind.

Another source we could pull the songs' length is Amazon, they offer more precise informations. I will work on that.   
 
Also I will probably move the Wiki parser in another class as well as the upcoming Amazon parser, so its a bit easier to read the code.

**Pull request merged**
